
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import 'i18next';


const monserratSans = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-montserrat-sans",
  weight: "100 900",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body > {children} </body>
    </html>
  );
}
